=== tim-pl-m/ProtoBuf-Replication-Prototype/replication.prototype.server/src/main/resources/Configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.ise.tu-berlin.de/AEC/Prototyping/Replication"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	targetNamespace="http://www.ise.tu-berlin.de/AEC/Prototyping/Replication">

	<xs:element name="configuration" type="ReplicationConfigurationType" />

	<xs:complexType name="ReplicationConfigurationType">
		<xs:sequence>
			<xs:element name="replicationpaths" type="ReplicationPathConfigurationType"
				maxOccurs="1" />
			<xs:element name="replicationnodes" type="ReplicationNodeConfigurationType"
				maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ReplicationNodeConfigurationType">
		<xs:sequence>
			<xs:element name="node" type="NodeType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="NodeType">
		<xs:attribute name="label" use="required" type="xs:string"/>
		<xs:attribute name="ipadress" type="xs:string"/>
		<xs:attribute name="port" type="xs:int"/>
	</xs:complexType>

	<xs:complexType name="ReplicationPathConfigurationType">
		<xs:sequence>
			<xs:element name="path" minOccurs="1" maxOccurs="unbounded"
				type="ReplicationPathType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ReplicationPathType">
		<xs:sequence>
			<xs:element name="link" minOccurs="1" maxOccurs="unbounded"
				type="ReplicationLinkType" />
		</xs:sequence>
		<xs:attribute name="start" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="ReplicationLinkType">
		<xs:attribute name="src" type="xs:string"></xs:attribute>
		<xs:attribute name="type" type="CommunicationEnumType"></xs:attribute>
		<xs:attribute name="target" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="QuorumReplicationLinkType">
		<xs:complexContent>
			<xs:extension base="ReplicationLinkType">
				<xs:sequence>
					<xs:element name="qparticipant" minOccurs="2" maxOccurs="unbounded">
						<xs:complexType>
							<xs:attribute name="name" use="required" type="xs:string" />
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="qsize" use="required" type="xs:positiveInteger" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="CommunicationEnumType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="quorum" />
			<xs:enumeration value="async" />
			<xs:enumeration value="sync" />
		</xs:restriction>
	</xs:simpleType>


</xs:schema>

=== tim-pl-m/ProtoBuf-Replication-Prototype/replication.prototype.coordinator/src/main/resources/Configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration
	xmlns="http://www.ise.tu-berlin.de/AEC/Prototyping/Replication"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="Configuration.xsd ">
	<replicationpaths>
		<path start="nodeA">
			<link src="nodeA" type="sync" target="nodeB" />
			<link src="nodeB" type="async" target="nodeC" />
		</path>
		<path  start="nodeB">
			<link  xsi:type="QuorumReplicationLinkType" src="nodeB" type="quorum" qsize="1">
				<qparticipant name="nodeA" />
				<qparticipant name="nodeC" />
			</link>
		</path>
		<path start="nodeC">
			<link src="nodeC" type="async" target="nodeA" />
			<link src="nodeC" type="async" target="nodeB" />
		</path>
	</replicationpaths>
	
	<replicationnodes>
	<!--  Private ip of amazon e2c nodes that are mapped to internal ids... -->
		<node label="nodeA" port="7183" />
		<node label="nodeB" port="7281" />
		<node label="nodeC" port="7384" /><!-- Identifikation via Ports -->
		
	</replicationnodes>
</configuration>

=== tim-pl-m/ProtoBuf-Replication-Prototype/replication.prototype.coordinator/src/main/resources/Configuration_01_Remote.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns="http://www.ise.tu-berlin.de/AEC/Prototyping/Replication"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="Configuration.xsd ">


	<replicationpaths>
		<path start="nodeA">
			<link src="nodeA" type="sync" target="nodeB" />
			<link src="nodeB" type="sync" target="nodeC" />
			<link src="nodeC" type="sync" target="nodeD" />
		</path>
	</replicationpaths>

	<replicationnodes>
		<!-- Private ip of amazon e2c nodes that are mapped to internal ids... -->
		<node label="nodeA" location="EU_WEST_1" />
		<node label="nodeB" location="US_EAST_1" />
		<node label="nodeC" location="US_WEST_1" />
		<node label="nodeD" location="SA_EAST_1" />
	</replicationnodes>
</configuration>

=== tim-pl-m/ProtoBuf-Replication-Prototype/replication.prototype.coordinator/src/main/resources/Configuration_01_Local.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns="http://www.ise.tu-berlin.de/AEC/Prototyping/Replication"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="Configuration.xsd ">


	<replicationpaths>
		<path start="nodeA">
			<link src="nodeA" type="sync" target="nodeB" />
			<link src="nodeB" type="sync" target="nodeC" />
			<link src="nodeC" type="sync" target="nodeD" />
		</path>
	</replicationpaths>

	<replicationnodes>
		<!-- Private ip of amazon e2c nodes that are mapped to internal ids... -->
		<node label="nodeA" ipadress="localhost" port="7183"  webserverport="8081" />
		<node label="nodeB" ipadress="localhost" port="7281"  webserverport="8082" />
		<node label="nodeC" ipadress="localhost" port="7384"  webserverport="8083" />
		<node label="nodeD" ipadress="localhost" port="7484"  webserverport="8084" />
	</replicationnodes>
</configuration>
